[build]
command = "npm ci && hugo --gc -b $URL" # change to suite your needs.
publish = "public"

[build.environment]
NODE_VERSION = "19"
HUGO_VERSION = "0.127.0"
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
GO_VERSION = "1.22.2"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
